print("jangan bandel")
print("selamat datang botak")
print("jadilah orang suksen")
print("lelaki sejati tidak mengemis cinta")
print("jangan lari woi siswa")
print("woi publick klo ketemu ling gua mening suren")
print("gua gabisa core? gua? gabisa? core?")
print("kangen dia")
print("saya bisa lari sampai 200000 kilo meter")
print("haiiii jelekkkk")